export const AUTHORIZATION = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE'
};
export const MAP = {
  ZOOM: 'ZOOM',
  SAVE_MARKER: 'SAVE_MARKER',
  GET_MARKERS: 'GET_MARKERS',
  ADD_MARKER: 'ADD_MARKER',
  REMOVE_MARKERS: 'REMOVE_MARKERS'
};
