export const AUTHORIZATION = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE'
};
export const MAP = {
  ZOOM: 'ZOOM',
  SAVE_MARKER: 'SAVE_MARKER',
  GET_MARKER: 'GET_MARKER'
};
